#this is for /context/ loading for updating page in 
#https://roboticdogs.actionkit.com/context/test_create?callback=actionkit.forms.onContextLoaded&form_name=act&action_id=117202230&ar=1&required=email&required=country&want_prefill_data=1&r=0.20345950596532325&url=https://roboticdogs.actionkit.com/event/scott-test_create/create/?action_id=117202230&update=1&want_prefill_data=1
#should be wrapped in actionkit.forms.onContextLoaded()
event_json = {
    "allowed_fields": {
        "action_id": 1,
        "address1": 1,
        "address2": 1,
        "akid": 1,
        "aktmid": 1,
        "auto_country": 1,
        "bat_phone": 1,
        "batch": 1,
        "city": 1,
        "country": 1,
        "email": 1,
        "emergency_phone": 1,
        "first_name": 1,
        "forget_me": 1,
        "form_name": 1,
        "from_uploader": 1,
        "home_fax_phone": 1,
        "home_phone": 1,
        "id": 1,
        "js": 1,
        "last_name": 1,
        "lists": 1,
        "loose": 1,
        "mailing_id": 1,
        "middle_name": 1,
        "mobile_phone": 1,
        "name": 1,
        "never_recognize": 1,
        "no_redirect_args": 1,
        "opt_in": 1,
        "page": 1,
        "phone": 1,
        "phone_type": 1,
        "postal": 1,
        "posted": 1,
        "prefix": 1,
        "rd": 1,
        "redirect": 1,
        "referer_from_url": 1,
        "referring_akid": 1,
        "region": 1,
        "remember_me": 1,
        "require_opt_in": 1,
        "required": 1,
        "skip_confirmation": 1,
        "skip_confirmation_in": 1,
        "source": 1,
        "state": 1,
        "status": 1,
        "strict": 1,
        "submit": 1,
        "submit_form": 1,
        "subscription_consent": 1,
        "suffix": 1,
        "suppress_subscribe": 1,
        "suppress_subscribe_in": 1,
        "t": 1,
        "taf": 1,
        "taf_body": 1,
        "taf_emails": 1,
        "taf_note": 1,
        "taf_only": 1,
        "taf_subject": 1,
        "terms": 1,
        "url": 1,
        "utf8": 1,
        "want_prefill_data": 1,
        "want_progress": 1,
        "work_fax_phone": 1,
        "work_phone": 1,
        "x": 1,
        "y": 1,
        "zip": 1
    },
    "blank": [
        "suffix",
        "prefix",
        "middle_name",
        "address2",
        "region"
    ],
    "form_name": "act",
    "lang_id": 100,
    "name": "Stephen King",
    "page": {
        "custom_fields": {
            "entity": "pac",
            "test_custom_event_field": "random text up to 100 characters"
        }
    },
    "prefill_data": {
        "action_id": "117202230",
        "action_referrer": "https://roboticdogs.actionkit.com/admin/core/pagefollowup/add/?page=1234",
        "address1": "123 Main St",
        "city": "Denver",
        "country": "United States",
        "email": "Stephen.King@example.com",
        "event_address1": "House at the bottom of the hill",
        "event_address2": "",
        "event_attendee_count": 5,
        "event_campaign": 27,
        "event_city": "Denver",
        "event_country": "United States",
        "event_creator": 34563841,
        "event_directions": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        "event_ends_at": None,
        "event_ends_at_utc": None,
        "event_host_is_confirmed": True,
        "event_id": 864,
        "event_is_approved": True,
        "event_is_private": False,
        "event_latitude": 40.870,
        "event_longitude": -103.59,
        "event_max_attendees": 20,
        "event_note_to_attendees": "Note to attendees.",
        "event_notes": "",
        "event_phone": "",
        "event_plus4": "1234",
        "event_postal": "80210",
        "event_public_description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        "event_region": "CO",
        "event_starts_at": "2016-08-18T09:00:00",
        "event_starts_at_ampm": "AM",
        "event_starts_at_date": "8/18/2017",
        "event_starts_at_time": "9:00",
        "event_starts_at_utc": "2016-08-18T15:00:00",
        "event_state": "CO",
        "event_status": "active",
        "event_title": "Canvas Stephen's neighborhood",
        "event_venue": "Haunted House",
        "event_zip": "80210",
        "first_name": "Stephen",
        "last_name": "King",
        "middle_name": "",
        "name": "Stephen King",
        "phone": "5551238765",
        "plus4": "1234",
        "prefix": "",
        "state": "CO",
        "suffix": "",
        "zip": "80210"
    },
    "required": [
        "event_starts_at_date",
        "event_host_ground_rules",
        "event_title",
        "event_address1",
        "event_public_description",
        "event_starts_at_time",
        "event_starts_at_ampm",
        "event_host_requirements",
        "event_venue"
    ],
    "text": {
        "error_TEMPLATE:invalid": "{0} is invalid.",
        "error_TEMPLATE:missing": "{0} is required.",
        "error_TEMPLATE:unexpected": "Unexpected field name {0}",
        "error_amount:double_pick": "Please either pick an amount from the list OR enter an amount.  You cannot use both in a single donation.",
        "error_amount:invalid": "The amount you entered does not appear to be valid.",
        "error_amount:maximum": "The amount you entered is too high.",
        "error_amount:minimum": "Sorry, donations below ${0} are not allowed.",
        "error_candidate:choose": "Please enter at least one donation amount.",
        "error_candidate:invalid": "Please enter a valid candidate. ({0})",
        "error_candidate:invalid_amount": "Please enter a valid amount for this candidate.",
        "error_card_num:cleared": "For your security, your card number has been cleared.",
        "error_card_num:duplicate": "Your previous transaction was successful.  If you wish to donate again please wait {0} minutes and try again.",
        "error_card_num:invalid": "The card number you entered is invalid.  Please try again.",
        "error_card_num:processor_error": "Sorry, your donation couldn't be processed.",
        "error_email:hosting": "You're already signed up as a host of this event.  If you want to register as an attendee as well, use another email address.",
        "error_event_cancelled:success": "Event cancelled.  You can search for other events below.",
        "error_event_contact_body:missing": "Please enter a message body.",
        "error_event_email_sent:success": "Message sent.",
        "error_event_host_ground_rules:missing": "Please check the box agreeing to the event host ground rules.",
        "error_event_host_requirements:missing": "Please check the box agreeing to the event host requirements.",
        "error_event_max_attendees:out_of_range": "Maximum attendees must be between {0} and {1}.",
        "error_event_page:wrong_update_page": "Sorry, this is the wrong page for updating this event. You should have been emailed a link to the correct host tools page when you created the event.",
        "error_event_place:try_another": "We can't find the event's location.  Check event city, postal code, state/region, and country (if any) for typos.",
        "error_event_roles_changed:success": "Role changed.",
        "error_event_roster_user_ids:cannot_demote_creator": "Sorry, the event's creator can't be removed from the host list.",
        "error_event_roster_user_ids:missing": "Please check off one or more people.",
        "error_event_signup_cancelled:success": "Event signup cancelled.  If you want, you can search for other events below.",
        "error_event_signup_ground_rules:missing": "Please check the box agreeing to the event attendee ground rules.",
        "error_event_starts_at_date:past": "Event cannot start in the past.",
        "error_event_updated:success": "Your event has been updated.",
        "error_event_users_removed:success": "Users removed.",
        "error_exp_date:invalid": "The expiration date you entered seems to be incorrect.  Use MMYY format.",
        "error_letter_text:letter_too_short": "Your letter is too short.",
        "error_lists:invalid": "Found a non-integer value in 'lists'.",
        "error_mailing_id:not_sent": "Unable to associate this mailing ID with account.",
        "error_media_target:duplicate_letter": "You have already contacted this paper. Please choose another.",
        "error_name:first_and_last": "First and last names are required.",
        "error_name:too_long": "Name must be shorter than 256 characters.",
        "error_payment_token:cookie invalid": "Your donation cannot be processed with the information we have. Please re-enter your information.",
        "error_payment_token:hash already used": "Your donation cannot be processed with the information we have. Please re-enter your information.",
        "error_payment_token:hash expired": "Your donation cannot be processed with the information we have. Please re-enter your information.",
        "error_payment_token:hash invalid": "Your donation cannot be processed with the information we have. Please re-enter your information.",
        "error_payment_token:needs_verification": "We don't recognize the browser or device you're using. Please verify your information below.",
        "error_payment_token:token does not belong to user": "Your donation cannot be processed with the information we have. Please re-enter your information.",
        "error_payment_token:token does not exist": "Your donation cannot be processed with the information we have. Please re-enter your information.",
        "error_payment_token:verification_failed": "The information you supplied does not match what we have on file. Please try again.",
        "error_payment_token:verification_impossible": "We cannot verify your information at this time. Please re-enter it below.",
        "error_product:choose": "Please enter the number of items you wish to receive.",
        "error_product:currency": "This product's pricing information is in the wrong currency.",
        "error_product:max": "I'm sorry, the maximum number of this item you may order is {0}.",
        "error_recurring_start:date_format": "recurring_start must be in the format YYYY-MM-DD",
        "error_recurringupdate:invalid": "You must provide either a new card or a new amount.",
        "error_reverse_donation:action_not_complete": "Sorry, we cannot reverse this donation with the information provided.",
        "error_reverse_donation:action_not_found": "Sorry, we cannot reverse this donation with the information provided.",
        "error_reverse_donation:action_user_mismatch": "Sorry, we cannot reverse this donation with the information provided.",
        "error_reverse_donation:cookie_invalid": "Sorry, we cannot reverse this donation with the information provided.",
        "error_reverse_donation:nonexistent_token": "Sorry, we cannot reverse this donation with the information provided.",
        "error_reverse_donation:order_does_not_exist": "Sorry, we cannot reverse this donation with the information provided.",
        "error_reverse_donation:order_not_completed": "Sorry, we cannot reverse this donation with the information provided.",
        "error_reverse_donation:reversal_failed": "Sorry, we cannot reverse this donation with the information provided.",
        "error_reverse_donation:reverse_window_elapsed": "Sorry, we cannot reverse this donation with the information provided.",
        "error_reverse_donation:user_not_recognized": "Sorry, we cannot reverse this donation with the information provided.",
        "error_subject:subject_too_long": "Your subject is too long.",
        "error_zip:doesnotmatch": "The address or ZIP code you gave do not match the billing address for the card.  Check for typos, or try another card or address.",
        "error_zip:not_targeted": "Sorry, this action isn't available where you live.",
        "field_address1": "street address",
        "field_address1_short": "address",
        "field_address2": "address line 2",
        "field_amount": "donation amount",
        "field_candidate": "candidate",
        "field_card_code": "credit card verification number",
        "field_card_num": "credit card number",
        "field_city": "city",
        "field_country": "country",
        "field_email": "email address",
        "field_email_short": "email",
        "field_event_address1": "event address",
        "field_event_directions": "directions to event",
        "field_event_max_attendees": "maximum number of attendees",
        "field_event_note_to_attendees": "note to event attendees",
        "field_event_postal": "event ZIP/postal code",
        "field_event_public_description": "event description",
        "field_event_starts_at": "event start date/time",
        "field_event_starts_at_date": "event start date",
        "field_event_starts_at_time": "event start time",
        "field_event_venue": "event venue",
        "field_event_zip": "event ZIP Code",
        "field_exp_date": "credit card expiration date",
        "field_exp_date_month": "credit card expiration month",
        "field_exp_date_year": "credit card expiration year",
        "field_lang": "language",
        "field_name": "name",
        "field_phone": "phone",
        "field_postal": "postal code",
        "field_shipping_address1": "shipping address",
        "field_shipping_city": "shipping city",
        "field_shipping_state": "shipping state",
        "field_shipping_zip": "shipping ZIP Code",
        "field_state": "state",
        "field_taf_emails": "one or more friends' email addresses",
        "field_zip": "ZIP Code"
    }
}
